import type { CSSProperties } from "react";

export const styles = {
  launcherRoot: {
    position: "fixed",
    right: 24,
    bottom: 24,
    zIndex: 1000,
    width: 360,
    maxWidth: "calc(100vw - 32px)",
  },
  launcher: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 9px",
    borderRadius: 999,
    background: "#fff",
    border: "1px solid rgba(22,71,52,0.16)",
    boxShadow: "0 18px 44px rgba(15,23,42,0.18)",
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
  },
  launcherIcon: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "#164734",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  launcherInput: {
    flex: 1,
    minWidth: 0,
    height: 34,
    border: 0,
    outline: "none",
    background: "transparent",
    color: "#111827",
    fontSize: 13.5,
    fontFamily: "inherit",
  },
  launcherButton: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    border: 0,
    background: "#164734",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  pageRoot: {
    minHeight: "calc(100vh - 44px)",
    background: "#f7f8f4",
    borderTop: "1px solid rgba(22,71,52,0.10)",
    display: "flex",
    justifyContent: "center",
    padding: "24px 16px 28px",
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
  },
  pageShell: {
    width: "min(960px, 100%)",
    minHeight: "calc(100vh - 104px)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    borderRadius: 16,
    background: "#fff",
    border: "1px solid rgba(22,71,52,0.14)",
    boxShadow: "0 22px 60px rgba(15,23,42,0.10)",
  },
  pageHeader: {
    display: "flex",
    alignItems: "center",
    gap: 13,
    padding: "18px 20px",
    borderBottom: "1px solid rgba(22,71,52,0.10)",
    background: "#fff",
  },
  pageAvatar: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    background: "#164734",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  pageTitle: {
    margin: 0,
    color: "#111827",
    fontSize: 20,
    lineHeight: 1.2,
    fontWeight: 720,
  },
  pageSubtitle: {
    margin: "3px 0 0",
    color: "#68716b",
    fontSize: 13,
    lineHeight: 1.35,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    flexShrink: 0,
    marginLeft: "auto",
  },
  loadPane: {
    padding: "14px 18px",
    borderBottom: "1px solid rgba(22,71,52,0.10)",
    background: "#f3f7f2",
    display: "flex",
    flexDirection: "column",
    gap: 9,
  },
  loadHeader: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    color: "#164734",
    fontSize: 12.5,
    fontWeight: 650,
  },
  progressTrack: {
    height: 5,
    background: "rgba(22,71,52,0.12)",
    borderRadius: 999,
    overflow: "hidden",
  },
  progressLabel: {
    fontSize: 11.5,
    color: "#68716b",
    textAlign: "right",
  },
  pageMessages: {
    flex: 1,
    overflowY: "auto",
    padding: "22px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 16,
    background: "#fbfbf8",
  },
  messageGroup: {
    display: "flex",
    flexDirection: "column",
    maxWidth: "min(680px, 86%)",
  },
  messageAuthor: {
    fontSize: 11,
    color: "#7b837d",
    marginBottom: 5,
    padding: "0 2px",
  },
  messageBubble: {
    padding: "11px 14px",
    borderRadius: 14,
    fontSize: 14,
    lineHeight: 1.55,
    whiteSpace: "normal",
    wordBreak: "break-word",
  },
  userBubble: {
    background: "#164734",
    color: "#fff",
    borderBottomRightRadius: 5,
  },
  assistantBubble: {
    background: "#fff",
    color: "#111827",
    border: "1px solid rgba(22,71,52,0.10)",
    borderBottomLeftRadius: 5,
  },
  messageActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  inlineActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    margin: "8px 0 10px",
  },
  markdownBlock: {
    display: "block",
  },
  markdownParagraph: {
    margin: "0 0 10px",
  },
  markdownHeading: {
    margin: "4px 0 8px",
    fontSize: 14,
    fontWeight: 720,
    color: "#111827",
  },
  orderedList: {
    margin: "0 0 10px 18px",
    padding: 0,
  },
  unorderedList: {
    margin: "0 0 10px 18px",
    padding: 0,
  },
  listItem: {
    margin: "0 0 6px",
    paddingLeft: 2,
  },
  inlineCode: {
    borderRadius: 5,
    background: "rgba(22,71,52,0.08)",
    color: "#164734",
    padding: "1px 4px",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: "0.92em",
  },
  actionButton: {
    border: "1px solid rgba(22,71,52,0.16)",
    background: "#fff",
    color: "#164734",
    borderRadius: 999,
    padding: "7px 10px",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    fontWeight: 650,
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  primaryActionButton: {
    background: "#164734",
    borderColor: "#164734",
    color: "#fff",
  },
  typingRow: {
    display: "flex",
    gap: 4,
    alignItems: "center",
    padding: "4px 0",
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "#a8b3ac",
  },
  pageInputRow: {
    padding: "14px 16px",
    borderTop: "1px solid rgba(22,71,52,0.10)",
    background: "#fff",
    display: "flex",
    gap: 10,
    alignItems: "flex-end",
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    background: "#164734",
    color: "#fff",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition: "opacity 0.15s, transform 0.12s",
  },
  gpuWarning: {
    margin: "14px 18px 0",
    padding: "10px 13px",
    background: "#fff7e8",
    color: "#8a5a06",
    borderRadius: 9,
    fontSize: 12.5,
    lineHeight: 1.45,
  },
  pageTextarea: {
    flex: 1,
    resize: "none",
    border: "1px solid rgba(22,71,52,0.16)",
    borderRadius: 14,
    padding: "10px 12px",
    fontSize: 14,
    fontFamily: "inherit",
    background: "#fbfbf8",
    color: "#111827",
    lineHeight: 1.5,
    minHeight: 40,
    maxHeight: 140,
    outline: "none",
  },
} satisfies Record<string, CSSProperties>;
