import type { CSSProperties } from "react";

export const styles = {
  root: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 12,
    fontFamily: "system-ui, sans-serif",
    position: "fixed",
    bottom: 24,
    right: 24,
    zIndex: 1000,
  },
  fab: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "#111",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "transform 0.15s",
    flexShrink: 0,
  },
  panel: {
    width: 390,
    maxWidth: "calc(100vw - 32px)",
    border: "0.5px solid rgba(0,0,0,0.15)",
    borderRadius: 12,
    overflow: "hidden",
    background: "#fff",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 4px 24px rgba(0,0,0,0.08)",
  },
  header: {
    padding: "14px 16px 12px",
    borderBottom: "0.5px solid rgba(0,0,0,0.08)",
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "#fff",
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "#111",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  loadPane: {
    padding: "16px 20px",
    borderBottom: "0.5px solid rgba(0,0,0,0.08)",
    background: "#f9f9f8",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  progressTrack: {
    height: 4,
    background: "rgba(0,0,0,0.08)",
    borderRadius: 2,
    overflow: "hidden",
  },
  messages: {
    flex: 1,
    overflowY: "auto",
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    maxHeight: 420,
    minHeight: 0,
  },
  inputRow: {
    padding: "10px 12px",
    borderTop: "0.5px solid rgba(0,0,0,0.08)",
    display: "flex",
    gap: 8,
    alignItems: "flex-end",
  },
  sendButton: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    background: "#111",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition: "opacity 0.15s, transform 0.12s",
  },
  gpuWarning: {
    margin: "12px 16px 0",
    padding: "10px 13px",
    background: "#FFF8E6",
    color: "#92600A",
    borderRadius: 8,
    fontSize: 12.5,
    lineHeight: 1.5,
  },
  textarea: {
    flex: 1,
    resize: "none",
    border: "0.5px solid rgba(0,0,0,0.15)",
    borderRadius: 8,
    padding: "8px 11px",
    fontSize: 13.5,
    fontFamily: "inherit",
    background: "#fff",
    color: "#111",
    lineHeight: 1.5,
    minHeight: 36,
    maxHeight: 100,
    outline: "none",
  },
} satisfies Record<string, CSSProperties>;
